# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the app using TypeScript compiler
RUN npm run build

CMD [ "node", "build/index.js" ]
